import { Roboto_Slab } from 'next/font/google'
import './globals.css'
import { StateContext } from './context/StateContext'
import Navber from './components/Navber'

const inter = Roboto_Slab({ 
  subsets: ['latin'],
  weight: '300',
  style : "normal"
 })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StateContext>
          <Navber />
          {children}
        </StateContext>
      </body>
    </html>
  )
}
